(() => {
  const en = {
    'Dashboard operativo':'Operations dashboard','Flota':'Fleet','Mantenimiento':'Maintenance','Operaciones':'Operations','Gestión inteligente de flotas':'Smart fleet management','Demo funcional local':'Local functional demo','Situación de la operación':'Operations overview','Visibilidad inmediata de activos, alertas y despachos.':'Immediate visibility into assets, alerts and dispatches.','Ver flota':'View fleet','Activos registrados':'Registered assets','Activos disponibles':'Available assets','Mantenimientos pendientes':'Pending maintenance','Despachos activos':'Active dispatches','Inventario actualizado':'Updated inventory','Listos para asignar':'Ready to assign','Atención programada':'Scheduled attention','Operación en curso':'Operation in progress','Próximas acciones':'Upcoming actions','Tipo':'Type','Activo / Ruta':'Asset / Route','Estado':'Status','Acción':'Action','Mantenimiento ':'Maintenance ','Completar':'Complete','No hay mantenimientos pendientes.':'There is no pending maintenance.','Inventario de flota':'Fleet inventory','Registra y consulta maquinaria, vehículos y su disponibilidad.':'Register and review machinery, vehicles and availability.','+ Registrar activo':'+ Register asset','Buscar por nombre o tipo':'Search by name or type','Todos los estados':'All statuses','Disponible':'Available','En operación':'In operation','En mantenimiento':'In maintenance','Restablecer demo':'Reset demo','Uso acumulado: ':'Current usage: ','Editar':'Edit','Dar de baja':'Remove','No se encontraron activos.':'No assets found.','Programa intervenciones y mantiene la flota disponible.':'Schedule interventions and keep the fleet available.','+ Programar mantenimiento':'+ Schedule maintenance','Orden':'Order','Fecha':'Date','No hay mantenimientos programados.':'There is no scheduled maintenance.','Coordina rutas, unidades y responsables de cada servicio.':'Coordinate routes, units and the person responsible for each service.','+ Crear despacho':'+ Create dispatch','Ruta':'Route','Unidad':'Unit','Responsable':'Responsible','En ruta':'On route','Programado':'Scheduled','Iniciar ruta':'Start route','Registrar activo':'Register asset','Editar activo':'Edit asset','Nombre':'Name','Uso actual (horas/km)':'Current usage (hours/km)','Cancelar':'Cancel','Guardar activo':'Save asset','Maquinaria':'Machinery','Camión':'Truck','Volquete':'Dump truck','Grúa':'Crane','Datos de demostración restablecidos.':'Demo data restored.','Mantenimiento programado para hoy.':'Maintenance scheduled for today.','No hay activos disponibles.':'There are no available assets.','Despacho creado y activo reservado.':'Dispatch created and asset reserved.','Activo dado de baja.':'Asset removed.','Mantenimiento completado.':'Maintenance completed.','Ruta iniciada.':'Route started.','Activo registrado.':'Asset registered.','Activo actualizado.':'Asset updated.'
  };
  let language = localStorage.getItem('technoload-webapp-language') || 'es';
  const invert = Object.fromEntries(Object.entries(en).map(([es, english]) => [english, es]));
  function replace(value) { const table = language === 'en' ? en : invert; const trimmed = value.trim(); return Object.prototype.hasOwnProperty.call(table, trimmed) ? value.replace(trimmed, table[trimmed]) : value; }
  function translate(root = document.body) { root.querySelectorAll('*').forEach((element) => { for (const node of element.childNodes) if (node.nodeType === Node.TEXT_NODE) node.nodeValue = replace(node.nodeValue); if (element.placeholder) element.placeholder = replace(element.placeholder); }); document.documentElement.lang = language; const button = document.querySelector('#language-switch'); button.textContent = language === 'es' ? 'EN' : 'ES'; button.setAttribute('aria-label', language === 'es' ? 'Change language' : 'Cambiar idioma'); }
  const observer = new MutationObserver(() => translate()); observer.observe(document.documentElement, { childList: true, subtree: true });
  document.addEventListener('DOMContentLoaded', () => { translate(); document.querySelector('#language-switch').addEventListener('click', () => { language = language === 'es' ? 'en' : 'es'; localStorage.setItem('technoload-webapp-language', language); translate(); }); });
})();
