const KEY = 'technoload-webapp-v2';
const seed = {
  assets: [
    { id:'A-001', name:'CAT 320 Excavator', type:'Machinery', usage:1842, status:'AVAILABLE' },
    { id:'A-002', name:'Volvo FMX Dump Truck', type:'Dump truck', usage:64500, status:'IN_OPERATION' },
    { id:'A-003', name:'XCMG QY25K Crane', type:'Crane', usage:3250, status:'IN_MAINTENANCE' },
    { id:'A-004', name:'Scania R450 Truck', type:'Truck', usage:98700, status:'AVAILABLE' }
  ],
  maintenance: [{id:'M-201',asset:'XCMG QY25K Crane',type:'Corrective',date:'2026-10-10'},{id:'M-202',asset:'CAT 320 Excavator',type:'Preventive',date:'2026-10-15'}],
  operations: [{id:'OP-31',route:'Lima → Ica',asset:'Volvo FMX Dump Truck',driver:'Marco Lopez',status:'ON_ROUTE'},{id:'OP-32',route:'Callao → Ate',asset:'Scania R450 Truck',driver:'Rosa Vargas',status:'SCHEDULED'}],
  membership: 'Professional'
};
let state = JSON.parse(localStorage.getItem(KEY) || 'null') || structuredClone(seed);
let view = location.hash.slice(1) || 'dashboard';
const app = document.querySelector('#app'), dialog = document.querySelector('#dialog'), form = document.querySelector('#asset-form');
const labels = { AVAILABLE:'Available', IN_OPERATION:'In operation', IN_MAINTENANCE:'In maintenance', ON_ROUTE:'On route', SCHEDULED:'Scheduled' };
const save = () => localStorage.setItem(KEY, JSON.stringify(state));
function toast(message) { const node = document.querySelector('#toast'); node.textContent = message; node.classList.add('show'); setTimeout(() => node.classList.remove('show'), 2800); }
function shell(title, content) {
  const nav = [['dashboard','▦','Dashboard'],['fleet','🚜','Fleet'],['rentals','▣','Rentals'],['maintenance','⚒','Maintenance'],['operations','⌖','Operations'],['memberships','★','Memberships']];
  const languageButton = window.TechnoLoadI18n?.language() === 'es' ? 'EN' : 'ES';
  return `<div class="shell"><aside class="side"><div class="brand"><i>T</i>TechnoLoad</div><nav>${nav.map(([id,icon,label]) => `<button class="${view===id?'active':''}" data-view="${id}"><span>${icon}</span>${label}</button>`).join('')}</nav><small>Smart fleet management<br>Functional local prototype</small></aside><main class="main"><header class="top"><b>${title}</b><span class="user">Flor Alvarez · Fleet Administrator</span><button class="language" data-action="language" aria-label="Change language">${languageButton}</button></header><section class="content">${content}</section></main></div>`;
}
function dashboard() {
  const available = state.assets.filter(item => item.status === 'AVAILABLE').length;
  const active = state.operations.filter(item => item.status === 'ON_ROUTE').length;
  return shell('Operations dashboard', `<div class="head"><div><h1>Operations overview</h1><p>Immediate visibility into assets, maintenance and dispatches.</p></div><button class="primary" data-view="fleet">View fleet</button></div><div class="metrics"><article class="metric"><span>Registered assets</span><b>${state.assets.length}</b><small>● Updated inventory</small></article><article class="metric"><span>Available assets</span><b>${available}</b><small>● Ready to assign</small></article><article class="metric"><span>Pending maintenance</span><b>${state.maintenance.length}</b><small>● Scheduled attention</small></article><article class="metric"><span>Active dispatches</span><b>${active}</b><small>● Operation in progress</small></article></div><section class="panel"><h2>Upcoming actions</h2><table><thead><tr><th>Type</th><th>Asset</th><th>Date</th><th>Action</th></tr></thead><tbody>${state.maintenance.map(item => `<tr><td>${item.type} maintenance</td><td>${item.asset}</td><td>${item.date}</td><td><button data-complete="${item.id}">Complete</button></td></tr>`).join('') || '<tr><td colspan="4">There is no pending maintenance.</td></tr>'}</tbody></table></section>`);
}
function fleet() { return shell('Fleet inventory', `<div class="head"><div><h1>Fleet inventory</h1><p>Register and review machinery, vehicles and availability.</p></div><button class="primary" data-action="new">+ Register asset</button></div><div class="toolbar"><input id="search" placeholder="Search by name or type"><select id="filter"><option value="">All statuses</option><option value="AVAILABLE">Available</option><option value="IN_OPERATION">In operation</option><option value="IN_MAINTENANCE">In maintenance</option></select><button data-action="reset">Reset demo</button></div><div id="asset-grid" class="grid">${cards(state.assets)}</div>`); }
function cards(items) { return items.length ? items.map(item => `<article class="asset"><header><h3>${item.name}</h3><span class="tag ${item.status}">${labels[item.status]}</span></header><p>${item.type}<br>Current usage: <b>${Number(item.usage).toLocaleString('en-US')}</b> h/km</p><footer><button data-edit="${item.id}">Edit</button><button class="danger" data-delete="${item.id}">Remove</button></footer></article>`).join('') : '<p class="empty">No assets found.</p>'; }
function rentals() { return shell('Rental requests', `<div class="head"><div><h1>Requests and rentals</h1><p>Review reservations and keep availability conflict-free.</p></div><button class="primary" data-action="rental">+ Create request</button></div><section class="panel"><table><thead><tr><th>Request</th><th>Customer</th><th>Asset</th><th>Status</th><th>Action</th></tr></thead><tbody><tr><td>R-1001</td><td>Andina Construction</td><td>CAT 320 Excavator</td><td><span class="tag IN_MAINTENANCE">Requested</span></td><td><button data-action="approve">Approve</button></td></tr><tr><td>R-1002</td><td>Pacific Works</td><td>Scania R450 Truck</td><td><span class="tag AVAILABLE">Confirmed</span></td><td>—</td></tr></tbody></table></section>`); }
function maintenance() { return shell('Maintenance', `<div class="head"><div><h1>Preventive maintenance</h1><p>Schedule interventions and keep the fleet available.</p></div><button class="primary" data-action="schedule">+ Schedule maintenance</button></div><section class="panel"><table><thead><tr><th>Order</th><th>Asset</th><th>Type</th><th>Date</th><th>Action</th></tr></thead><tbody>${state.maintenance.map(item => `<tr><td>${item.id}</td><td>${item.asset}</td><td>${item.type}</td><td>${item.date}</td><td><button data-complete="${item.id}">Complete</button></td></tr>`).join('') || '<tr><td colspan="5">There is no scheduled maintenance.</td></tr>'}</tbody></table></section>`); }
function operations() { return shell('Operations', `<div class="head"><div><h1>Operations and dispatches</h1><p>Coordinate routes, units and each service owner.</p></div><button class="primary" data-action="operation">+ Create dispatch</button></div><section class="panel"><table><thead><tr><th>Order</th><th>Route</th><th>Unit</th><th>Owner</th><th>Status</th><th>Action</th></tr></thead><tbody>${state.operations.map(item => `<tr><td>${item.id}</td><td>${item.route}</td><td>${item.asset}</td><td>${item.driver}</td><td><span class="tag ${item.status==='ON_ROUTE'?'IN_OPERATION':'IN_MAINTENANCE'}">${labels[item.status]}</span></td><td>${item.status==='SCHEDULED'?`<button data-start="${item.id}">Start route</button>`:'—'}</td></tr>`).join('')}</tbody></table></section>`); }
function memberships() { const plans = [['Starter','S/ 149','Up to 10 assets'],['Professional','S/ 349','Up to 50 assets'],['Enterprise','Custom','Unlimited assets']]; return shell('Memberships', `<div class="head"><div><h1>Membership and billing</h1><p>Your active plan is <b>${state.membership}</b>. Select a plan to update this functional prototype.</p></div></div><div class="grid">${plans.map(([name,price,detail]) => `<article class="asset"><header><h3>${name}</h3><span class="tag ${name===state.membership?'AVAILABLE':'IN_OPERATION'}">${name===state.membership?'Active':'Plan'}</span></header><p><b style="font-size:1.5rem">${price}</b><br>${detail}<br>Fleet, maintenance and operations tools.</p><footer><button class="${name===state.membership?'':'primary'}" ${name===state.membership?'disabled':''} data-plan="${name}">${name===state.membership?'Current plan':`Choose ${name}`}</button></footer></article>`).join('')}</div>`); }
function render() { location.hash = view; const page = {fleet, rentals, maintenance, operations, memberships}[view] || dashboard; app.innerHTML = page(); window.TechnoLoadI18n?.translate(document); }
function openAsset(item = {id:'',name:'',type:'Machinery',usage:0,status:'AVAILABLE'}) { document.querySelector('#dialog-title').textContent = item.id ? 'Edit asset' : 'Register asset'; for (const key of ['id','name','type','usage','status']) document.querySelector(`#asset-${key}`).value = item[key]; dialog.showModal(); }
document.addEventListener('click', event => { const button = event.target.closest('button'); if (!button) return; if (button.dataset.view) { view = button.dataset.view; render(); return; } if (button.dataset.action==='language') { window.TechnoLoadI18n?.toggle(); render(); return; } if (button.dataset.action==='new') openAsset(); if (button.dataset.action==='reset') { state=structuredClone(seed);save();render();toast('Demo data restored.'); } if (button.dataset.action==='schedule') { const asset=state.assets.find(item=>item.status!=='IN_MAINTENANCE') || state.assets[0]; state.maintenance.push({id:`M-${Date.now().toString().slice(-4)}`,asset:asset.name,type:'Preventive',date:new Date().toISOString().slice(0,10)});save();render();toast('Maintenance scheduled.'); } if (button.dataset.action==='operation') { const asset=state.assets.find(item=>item.status==='AVAILABLE'); if (!asset) return toast('There are no available assets.'); asset.status='IN_OPERATION';state.operations.push({id:`OP-${Date.now().toString().slice(-4)}`,route:'Lima → Chancay',asset:asset.name,driver:'Assigned operator',status:'SCHEDULED'});save();render();toast('Dispatch created and asset reserved.'); } if (button.dataset.action==='approve') toast('Rental request approved.'); if (button.dataset.action==='rental') toast('Rental request created.'); if (button.dataset.edit) openAsset(state.assets.find(item=>item.id===button.dataset.edit)); if (button.dataset.delete) { state.assets=state.assets.filter(item=>item.id!==button.dataset.delete);save();render();toast('Asset removed.'); } if (button.dataset.complete) { state.maintenance=state.maintenance.filter(item=>item.id!==button.dataset.complete);save();render();toast('Maintenance completed.'); } if (button.dataset.start) { state.operations.find(item=>item.id===button.dataset.start).status='ON_ROUTE';save();render();toast('Route started.'); } if (button.dataset.plan) { state.membership=button.dataset.plan;save();render();toast(`${state.membership} membership is now active.`); } });
document.addEventListener('input', event => { if (event.target.id==='search') { const term=event.target.value.toLowerCase(), filter=document.querySelector('#filter').value; document.querySelector('#asset-grid').innerHTML=cards(state.assets.filter(item=>(item.name+item.type).toLowerCase().includes(term)&&(!filter||item.status===filter))); } });
document.addEventListener('change', event => { if (event.target.id==='filter') document.querySelector('#search').dispatchEvent(new Event('input')); });
form.addEventListener('submit', event => { if (event.submitter?.value==='cancel') return; event.preventDefault(); const item={id:document.querySelector('#asset-id').value||`A-${Date.now().toString().slice(-4)}`,name:document.querySelector('#asset-name').value,type:document.querySelector('#asset-type').value,usage:Number(document.querySelector('#asset-usage').value),status:document.querySelector('#asset-status').value}; const index=state.assets.findIndex(asset=>asset.id===item.id); if(index<0) state.assets.push(item); else state.assets[index]=item;save();dialog.close();render();toast(index<0?'Asset registered.':'Asset updated.'); });
render();
