import { CommonModule } from '@angular/common';
import { Component, computed, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Asset, AssetStatus } from './models';

type View = 'dashboard' | 'fleet' | 'maintenance' | 'operations';
const seed: Asset[] = [
  {id:'A-001',name:'Excavadora CAT 320',type:'Maquinaria',usage:1842,status:'AVAILABLE'},
  {id:'A-002',name:'Volquete Volvo FMX',type:'Volquete',usage:64500,status:'IN_OPERATION'},
  {id:'A-003',name:'Grúa XCMG QY25K',type:'Grúa',usage:3250,status:'IN_MAINTENANCE'},
  {id:'A-004',name:'Camión Scania R450',type:'Camión',usage:98700,status:'AVAILABLE'}];

@Component({ selector:'app-root', standalone:true, imports:[CommonModule, FormsModule], template:`
<div class="shell"><aside class="side"><div class="brand"><i>T</i>TechnoLoad</div><nav>
  <button *ngFor="let item of nav" [class.active]="view()===item.id" (click)="view.set(item.id)">{{item.icon}}<span>{{item.label}}</span></button>
</nav><small>Gestión inteligente de flotas<br>Angular + TypeScript</small></aside>
<main class="main"><header class="top"><b>{{title()}}</b><span class="user">Flor Álvarez · Administradora de flota</span></header><section class="content">
  <ng-container [ngSwitch]="view()">
    <section *ngSwitchCase="'dashboard'"><div class="head"><div><h1>Situación de la operación</h1><p>Visibilidad inmediata de activos, alertas y despachos.</p></div><button class="primary" (click)="view.set('fleet')">Ver flota</button></div>
      <div class="metrics"><article class="metric"><span>Activos registrados</span><b>{{assets().length}}</b><small>● Inventario actualizado</small></article><article class="metric"><span>Activos disponibles</span><b>{{available()}}</b><small>● Listos para asignar</small></article><article class="metric"><span>Mantenimientos pendientes</span><b>{{maintenance().length}}</b><small>● Atención programada</small></article><article class="metric"><span>Despachos activos</span><b>{{activeOperations()}}</b><small>● Operación en curso</small></article></div>
      <section class="panel"><h2>Próximas acciones</h2><table><tr><th>Tipo</th><th>Activo</th><th>Fecha</th><th>Acción</th></tr><tr *ngFor="let m of maintenance()"><td>Mantenimiento {{m.type}}</td><td>{{m.asset}}</td><td>{{m.date}}</td><td><button (click)="complete(m.id)">Completar</button></td></tr></table></section></section>
    <section *ngSwitchCase="'fleet'"><div class="head"><div><h1>Inventario de flota</h1><p>Registra y consulta maquinaria, vehículos y disponibilidad.</p></div><button class="primary" (click)="newAsset()">+ Registrar activo</button></div><div class="toolbar"><input [(ngModel)]="query" placeholder="Buscar por nombre o tipo"><select [(ngModel)]="statusFilter"><option value="">Todos los estados</option><option value="AVAILABLE">Disponible</option><option value="IN_OPERATION">En operación</option><option value="IN_MAINTENANCE">Mantenimiento</option></select><button (click)="reset()">Restablecer demo</button></div><div class="grid"><article class="asset" *ngFor="let a of filteredAssets()"><header><h3>{{a.name}}</h3><span class="tag {{a.status}}">{{label(a.status)}}</span></header><p>{{a.type}}<br>Uso acumulado: <b>{{a.usage | number}}</b> h/km</p><footer><button (click)="edit(a)">Editar</button><button class="danger" (click)="remove(a.id)">Dar de baja</button></footer></article></div></section>
    <section *ngSwitchCase="'maintenance'"><div class="head"><div><h1>Mantenimiento preventivo</h1><p>Programa intervenciones y mantiene la flota disponible.</p></div><button class="primary" (click)="schedule()">+ Programar mantenimiento</button></div><section class="panel"><table><tr><th>Orden</th><th>Activo</th><th>Tipo</th><th>Fecha</th><th></th></tr><tr *ngFor="let m of maintenance()"><td>{{m.id}}</td><td>{{m.asset}}</td><td>{{m.type}}</td><td>{{m.date}}</td><td><button (click)="complete(m.id)">Completar</button></td></tr></table></section></section>
    <section *ngSwitchCase="'operations'"><div class="head"><div><h1>Operaciones y despachos</h1><p>Coordina rutas, unidades y responsables.</p></div><button class="primary" (click)="addOperation()">+ Crear despacho</button></div><section class="panel"><table><tr><th>Orden</th><th>Ruta</th><th>Unidad</th><th>Responsable</th><th>Estado</th><th></th></tr><tr *ngFor="let o of operations()"><td>{{o.id}}</td><td>{{o.route}}</td><td>{{o.asset}}</td><td>{{o.driver}}</td><td><span class="tag {{o.status==='En ruta'?'IN_OPERATION':'IN_MAINTENANCE'}}">{{o.status}}</span></td><td><button *ngIf="o.status==='Programado'" (click)="start(o.id)">Iniciar ruta</button></td></tr></table></section></section>
  </ng-container>
</section></main></div>
<dialog #dialog><form method="dialog" (ngSubmit)="save(dialog)"><header><b>{{editing ? 'Editar activo' : 'Registrar activo'}}</b><button type="button" (click)="dialog.close()">×</button></header><label>Nombre<input required [(ngModel)]="draft.name" name="name"></label><label>Tipo<select [(ngModel)]="draft.type" name="type"><option>Maquinaria</option><option>Camión</option><option>Volquete</option><option>Grúa</option></select></label><label>Uso actual<input type="number" min="0" required [(ngModel)]="draft.usage" name="usage"></label><label>Estado<select [(ngModel)]="draft.status" name="status"><option value="AVAILABLE">Disponible</option><option value="IN_OPERATION">En operación</option><option value="IN_MAINTENANCE">En mantenimiento</option></select></label><menu><button type="button" (click)="dialog.close()">Cancelar</button><button class="primary">Guardar activo</button></menu></form></dialog>
<div id="toast" [class.show]="toast()">{{toast()}}</div>` })
export class AppComponent {
  readonly nav: {id:View; icon:string; label:string}[]=[{id:'dashboard',icon:'▦',label:'Dashboard'},{id:'fleet',icon:'🚜',label:'Flota'},{id:'maintenance',icon:'⚒',label:'Mantenimiento'},{id:'operations',icon:'⌖',label:'Operaciones'}];
  view=signal<View>('dashboard'); assets=signal<Asset[]>(this.read('assets',seed)); maintenance=signal([{id:'M-201',asset:'Grúa XCMG QY25K',type:'Correctivo',date:'2026-10-10'},{id:'M-202',asset:'Excavadora CAT 320',type:'Preventivo',date:'2026-10-15'}]); operations=signal([{id:'OP-31',route:'Lima → Ica',asset:'Volquete Volvo FMX',driver:'Marco López',status:'En ruta'},{id:'OP-32',route:'Callao → Ate',asset:'Camión Scania R450',driver:'Rosa Vargas',status:'Programado'}]);
  query=''; statusFilter=''; editing=false; draft:Asset={id:'',name:'',type:'Maquinaria',usage:0,status:'AVAILABLE'}; toast=signal('');
  available=computed(()=>this.assets().filter(a=>a.status==='AVAILABLE').length); activeOperations=computed(()=>this.operations().filter(o=>o.status==='En ruta').length); title=computed(()=>({dashboard:'Dashboard operativo',fleet:'Flota',maintenance:'Mantenimiento',operations:'Operaciones'}[this.view()]));
  read<T>(key:string,fallback:T):T { try{return JSON.parse(localStorage.getItem('technoload-ts-'+key)??'') as T}catch{return fallback} } persist(){localStorage.setItem('technoload-ts-assets',JSON.stringify(this.assets()))} notice(message:string){this.toast.set(message);setTimeout(()=>this.toast.set(''),2600)} label(s:AssetStatus){return ({AVAILABLE:'Disponible',IN_OPERATION:'En operación',IN_MAINTENANCE:'En mantenimiento'}[s])} filteredAssets(){const q=this.query.toLowerCase();return this.assets().filter(a=>(!q||(a.name+a.type).toLowerCase().includes(q))&&(!this.statusFilter||a.status===this.statusFilter))}
  newAsset(){this.editing=false;this.draft={id:'',name:'',type:'Maquinaria',usage:0,status:'AVAILABLE'};(document.querySelector('dialog') as HTMLDialogElement).showModal()} edit(a:Asset){this.editing=true;this.draft={...a};(document.querySelector('dialog') as HTMLDialogElement).showModal()} save(dialog:HTMLDialogElement){const item={...this.draft,id:this.draft.id||`A-${Date.now().toString().slice(-4)}`};this.assets.update(list=>this.editing?list.map(a=>a.id===item.id?item:a):[...list,item]);this.persist();dialog.close();this.notice('Activo guardado.')} remove(id:string){this.assets.update(list=>list.filter(a=>a.id!==id));this.persist();this.notice('Activo dado de baja.')} reset(){this.assets.set(structuredClone(seed));this.persist();this.notice('Datos restablecidos.')} complete(id:string){this.maintenance.update(list=>list.filter(m=>m.id!==id));this.notice('Mantenimiento completado.')} schedule(){const asset=this.assets()[0];if(asset){this.maintenance.update(list=>[...list,{id:`M-${Date.now().toString().slice(-4)}`,asset:asset.name,type:'Preventivo',date:new Date().toISOString().slice(0,10)}]);this.notice('Mantenimiento programado.')}} addOperation(){const asset=this.assets().find(a=>a.status==='AVAILABLE');if(!asset){this.notice('No hay activos disponibles.');return}this.assets.update(list=>list.map(a=>a.id===asset.id?{...a,status:'IN_OPERATION' as AssetStatus}:a));this.operations.update(list=>[...list,{id:`OP-${Date.now().toString().slice(-4)}`,route:'Lima → Chancay',asset:asset.name,driver:'Operador asignado',status:'Programado'}]);this.persist();this.notice('Despacho creado.')} start(id:string){this.operations.update(list=>list.map(o=>o.id===id?{...o,status:'En ruta'}:o));this.notice('Ruta iniciada.')} }
